[platformio]
cache_dir = .cache
build_cache_dir = .build_cache
default_envs = badge  ; Set the default environment to "badge"

[env:badge]
platform = espressif8266
board = esp_wroom_02
framework = arduino
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.2m1m.ld
upload_speed = 921600
monitor_speed = 9600
lib_deps =
	fastled/FastLED@3.7.8
	bblanchon/ArduinoJson@^7.3.0
	adafruit/Adafruit GFX Library@^1.11.11
	adafruit/Adafruit SSD1306@^2.5.13
	neu-rah/ArduinoMenu library@^4.21.4
	neu-rah/streamFlow@0.0.0-alpha+sha.bf16ce8926
	xreef/PCF8574 library@^2.3.7
	paulstoffregen/OneWire@2.3.8
	TaskScheduler@^3.8.5
	thingsboard/TBPubSubClient@^2.11.0
	adafruit/Adafruit DS248x@^1.2.0
	rweather/Crypto@^0.4.0
build_flags =
	-std=gnu++20
;extra_scripts = post:scripts/upload_to_s3.py

;[env:kiosk]
;pextends = env:badge
;build_flags =
;	-std=gnu++20
;	-DENABLE_KIOSK_MODE
;extra_scripts = post:scripts/upload_to_s3.py
